# Generated by Django 4.2.26 on 2025-11-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='CarRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('out_of_town', models.BooleanField(default=False)),
                ('needs_driver', models.BooleanField(default=False)),
                ('subsidiary', models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], default='cell_insurance', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_level1', to=settings.AUTH_USER_MODEL)),
                ('approver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_level2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=32, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('fuel_type', models.CharField(blank=True, max_length=32)),
                ('engine_capacity', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('accessories', models.TextField(blank=True)),
                ('service_interval_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('gm', 'GM'), ('ceo', 'CEO'), ('mis', 'MIS Admin'), ('driver', 'Driver')], default='employee', max_length=32)),
                ('subsidiary', models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], default='cell_insurance', max_length=32)),
                ('is_dedicated_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_level', models.CharField(blank=True, max_length=64)),
                ('condition_notes', models.TextField(blank=True)),
                ('accessories_missing', models.TextField(blank=True)),
                ('damages', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='handover_photos/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='fleet.carrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_handover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
