# Generated by Django 4.2.26 on 2025-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverchecklist',
            name='photo',
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='additional_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='additional_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='additional_photo3',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='checklist_document',
            field=models.FileField(blank=True, help_text='PDF, Image, or Scanned document', null=True, upload_to='handover_checklists/'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='return_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
