# Generated by Django 4.2.26 on 2025-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_handoverchecklist_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subsidiary',
            field=models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], default='cell_insurance', max_length=32),
        ),
    ]
