# Generated by Django 4.2.26 on 2026-01-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0003_vehicle_branch_vehicle_subsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrequest',
            name='ceo_approved_by',
            field=models.ForeignKey(blank=True, help_text='CEO approval for managers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='gm_approved_by',
            field=models.ForeignKey(blank=True, help_text='GM approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, help_text='Supervisor approval for general employees', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_type',
            field=models.CharField(choices=[('GENERAL_EMPLOYEE', 'General Employee'), ('MANAGER', 'Manager')], default='GENERAL_EMPLOYEE', help_text='Classification for approval routing', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Immediate supervisor for general employees', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='approver1',
            field=models.ForeignKey(blank=True, help_text='Legacy field - kept for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_level1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='approver2',
            field=models.ForeignKey(blank=True, help_text='Legacy field - kept for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_level2', to=settings.AUTH_USER_MODEL),
        ),
    ]
