# Generated by Django 4.2.26 on 2026-01-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0004_carrequest_ceo_approved_by_carrequest_gm_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='carrequest',
            name='selected_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor selected by employee at request time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
