# Generated by Django 6.0 on 2026-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_profile_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if request was rejected', null=True),
        ),
    ]
