# Generated by Django 6.0 on 2026-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_carrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverchecklist',
            name='aa_zimbabwe_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='aa_zimbabwe_card_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='alarm_system_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='alarm_system_functional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='brake_lights_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='brake_lights_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='car_radio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='car_radio_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='floor_mats',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='floor_mats_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='fuel_reading',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='hand_brake_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='hand_brake_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='indicators_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='indicators_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='jack',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='jack_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='lock_nuts_spanner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='lock_nuts_spanner_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='mileage_kms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='park_lights_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='park_lights_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='reflectors_installed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='reflectors_installed_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='scratches_dents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='seat_belts_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='seat_belts_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='seat_covers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='seat_covers_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='spare_wheel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='spare_wheel_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='spare_wheel_hatchet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='spare_wheel_hatchet_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='tool_box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='tool_box_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='vehicle_insurance_disk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='vehicle_insurance_disk_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='vehicle_licence_disk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='vehicle_licence_disk_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='view_mirrors_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='view_mirrors_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='wheel_covers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='wheel_covers_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='wheel_spanner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='wheel_spanner_comments',
            field=models.TextField(blank=True),
        ),
    ]
