# Generated by Django 6.0 on 2026-01-11 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_handoverchecklist_aa_zimbabwe_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('A Service', 'A Service'), ('B Service', 'B Service'), ('C Service', 'C Service'), ('Major Service', 'Major Service'), ('Oil Change', 'Oil Change'), ('Brake Service', 'Brake Service'), ('Tire Replacement', 'Tire Replacement'), ('General Repair', 'General Repair'), ('Other', 'Other')], max_length=64)),
                ('service_company', models.CharField(max_length=128)),
                ('mileage_at_service', models.PositiveIntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the service')),
                ('next_service_due', models.PositiveIntegerField(blank=True, help_text='Mileage when next service is due', null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_recorded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
