# Generated by Django 4.2.26 on 2026-01-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_servicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverchecklist',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Issues Found'), ('needs_review', 'Needs Additional Review')], default='pending', max_length=20),
        ),
    ]
