# Generated by Django 4.2.26 on 2026-01-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_handoverchecklist_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Current vehicle mileage', null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Driver assigned to vehicle', max_length=128),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='upload_month',
            field=models.CharField(blank=True, help_text='Month of upload (e.g., July 2025)', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle_description',
            field=models.CharField(blank=True, help_text='Vehicle description for standalone tracking', max_length=256),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle_reg_number',
            field=models.CharField(blank=True, help_text='Registration number for standalone tracking', max_length=32),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('A Service', 'A Service'), ('B Service', 'B Service'), ('C Service', 'C Service'), ('Major Service', 'Major Service'), ('Oil Change', 'Oil Change'), ('Brake Service', 'Brake Service'), ('Tire Replacement', 'Tire Replacement'), ('General Repair', 'General Repair'), ('First Service', 'First Service'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='fleet.vehicle'),
        ),
    ]
