# Generated by Django 4.2.27 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_servicerecord_current_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned'), ('completed', 'Completed')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='subsidiary',
            field=models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], db_index=True, default='cell_insurance', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_dedicated_driver',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('gm', 'GM'), ('ceo', 'CEO'), ('mis', 'MIS Admin'), ('driver', 'Driver')], db_index=True, default='employee', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subsidiary',
            field=models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], db_index=True, default='cell_insurance', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subsidiary',
            field=models.CharField(choices=[('cell_insurance', 'Cell Insurance'), ('cellmed', 'CellMed'), ('nectacare', 'Nectacare')], db_index=True, default='cell_insurance', max_length=32),
        ),
        migrations.AddIndex(
            model_name='carrequest',
            index=models.Index(fields=['status'], name='fleet_carre_status_e51bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='carrequest',
            index=models.Index(fields=['subsidiary'], name='fleet_carre_subsidi_edc6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='carrequest',
            index=models.Index(fields=['requester', 'status'], name='fleet_carre_request_c6f090_idx'),
        ),
        migrations.AddIndex(
            model_name='carrequest',
            index=models.Index(fields=['created_at'], name='fleet_carre_created_3cc553_idx'),
        ),
        migrations.AddIndex(
            model_name='carrequest',
            index=models.Index(fields=['status', 'assigned_vehicle'], name='fleet_carre_status_5cd527_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='fleet_profi_role_26e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['subsidiary'], name='fleet_profi_subsidi_a7e475_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_dedicated_driver'], name='fleet_profi_is_dedi_a1f186_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='fleet_vehic_status_f5cfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['subsidiary'], name='fleet_vehic_subsidi_9a5a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'created_at'], name='fleet_vehic_status_622b15_idx'),
        ),
    ]
