# Generated by Django 4.2.27 on 2026-01-31 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0011_alter_carrequest_created_at_alter_carrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=64)),
                ('engine_number', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ambulances/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_call', 'On Call'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=32)),
                ('service_interval_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('base_location', models.CharField(blank=True, help_text='Primary station/location', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='e.g., Oxygen Cylinder, Stretcher, Defibrillator', max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('present', 'Present and Functional'), ('missing', 'Missing'), ('damaged', 'Damaged/Non-functional'), ('expired', 'Expired')], default='present', max_length=32)),
                ('expiry_date', models.DateField(blank=True, help_text='For items like oxygen, medications', null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ambulance', 'equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('patient_name', models.CharField(blank=True, help_text='Patient name (if applicable)', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=32)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('routine_service', 'Routine Service'), ('major_service', 'Major Service'), ('oil_change', 'Oil Change'), ('brake_service', 'Brake Service'), ('tire_replacement', 'Tire Replacement'), ('equipment_calibration', 'Equipment Calibration'), ('body_repair', 'Body Repair'), ('general_repair', 'General Repair'), ('other', 'Other')], max_length=64)),
                ('service_company', models.CharField(max_length=128)),
                ('mileage_at_service', models.PositiveIntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Details about the service performed')),
                ('next_service_due', models.PositiveIntegerField(blank=True, help_text='Mileage when next service is due', null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('receipt', models.FileField(blank=True, help_text='Service receipt/invoice', null=True, upload_to='ambulance_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(help_text='e.g., Emergency Response, Patient Transfer', max_length=255)),
                ('start_location', models.CharField(blank=True, max_length=255)),
                ('end_location', models.CharField(blank=True, max_length=255)),
                ('start_mileage', models.PositiveIntegerField()),
                ('end_mileage', models.PositiveIntegerField()),
                ('fuel_added', models.DecimalField(blank=True, decimal_places=2, help_text='Liters of fuel added', max_digits=6, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_receipt', models.FileField(blank=True, null=True, upload_to='ambulance_fuel_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='module',
            field=models.CharField(choices=[('poolcar', 'Pool Car Manager'), ('ambulance', 'Ambulance Manager'), ('both', 'Both Modules')], db_index=True, default='poolcar', help_text='Which module(s) the user has access to', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('gm', 'GM'), ('ceo', 'CEO'), ('mis', 'MIS Admin'), ('driver', 'Driver'), ('ambulance_admin', 'Ambulance Admin'), ('nectacare_head', 'Nectacare Head')], db_index=True, default='employee', max_length=32),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['module'], name='fleet_profi_module_b534df_idx'),
        ),
        migrations.AddField(
            model_name='ambulanceusagerecord',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='fleet.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulanceusagerecord',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulanceservicerecord',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='fleet.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulanceservicerecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_services_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='assigned_ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulanceequipment',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='fleet.ambulance'),
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['status'], name='fleet_ambul_status_7d0ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['status', 'created_at'], name='fleet_ambul_status_af4302_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['status'], name='fleet_ambul_status_c473e5_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['requested_date'], name='fleet_ambul_request_091d4c_idx'),
        ),
    ]
