# Generated by Django 4.2.27 on 2026-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_ambulance_ambulanceequipment_ambulancerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('gm', 'GM'), ('ceo', 'CEO'), ('mis', 'MIS Admin'), ('driver', 'Driver'), ('ambulance_admin', 'Ambulance Admin'), ('ambulance_mis', 'Ambulance MIS Admin'), ('nectacare_head', 'Nectacare Head')], db_index=True, default='employee', max_length=32),
        ),
    ]
