# Generated by Django 4.2.27 on 2026-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceusagerecord',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Name of the driver assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='ambulanceusagerecord',
            name='driver_phone',
            field=models.CharField(blank=True, help_text='Driver contact number', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulanceusagerecord',
            name='end_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
