# Generated by Django 4.2.27 on 2026-02-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0014_ambulanceusagerecord_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceHandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_mileage', models.PositiveIntegerField()),
                ('fuel_level', models.CharField(max_length=64)),
                ('condition_notes', models.TextField(blank=True)),
                ('stretcher_condition', models.CharField(blank=True, max_length=10, null=True)),
                ('stretcher_comments', models.TextField(blank=True)),
                ('oxygen_cylinders', models.CharField(blank=True, max_length=10, null=True)),
                ('oxygen_cylinders_comments', models.TextField(blank=True)),
                ('first_aid_kit', models.CharField(blank=True, max_length=10, null=True)),
                ('first_aid_kit_comments', models.TextField(blank=True)),
                ('defibrillator', models.CharField(blank=True, max_length=10, null=True)),
                ('defibrillator_comments', models.TextField(blank=True)),
                ('spinal_board', models.CharField(blank=True, max_length=10, null=True)),
                ('spinal_board_comments', models.TextField(blank=True)),
                ('medical_supplies', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_supplies_comments', models.TextField(blank=True)),
                ('lights_sirens_functional', models.CharField(blank=True, max_length=10, null=True)),
                ('lights_sirens_comments', models.TextField(blank=True)),
                ('brake_lights_functioning', models.CharField(blank=True, max_length=10, null=True)),
                ('brake_lights_comments', models.TextField(blank=True)),
                ('indicators_functioning', models.CharField(blank=True, max_length=10, null=True)),
                ('indicators_comments', models.TextField(blank=True)),
                ('communication_radio', models.CharField(blank=True, max_length=10, null=True)),
                ('communication_radio_comments', models.TextField(blank=True)),
                ('spare_wheel', models.CharField(blank=True, max_length=10, null=True)),
                ('spare_wheel_comments', models.TextField(blank=True)),
                ('jack_tools', models.CharField(blank=True, max_length=10, null=True)),
                ('jack_tools_comments', models.TextField(blank=True)),
                ('fire_extinguisher', models.CharField(blank=True, max_length=10, null=True)),
                ('fire_extinguisher_comments', models.TextField(blank=True)),
                ('reflectors_installed', models.CharField(blank=True, max_length=10, null=True)),
                ('reflectors_comments', models.TextField(blank=True)),
                ('interior_cleanliness', models.CharField(blank=True, max_length=10, null=True)),
                ('interior_cleanliness_comments', models.TextField(blank=True)),
                ('sanitization_completed', models.CharField(blank=True, max_length=10, null=True)),
                ('sanitization_comments', models.TextField(blank=True)),
                ('damages', models.TextField(blank=True)),
                ('scratches_dents', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('checklist_document', models.FileField(blank=True, null=True, upload_to='ambulance_handover_checklists/')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='ambulance_handover_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='ambulance_handover_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='ambulance_handover_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Issues Found'), ('needs_review', 'Needs Additional Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet.ambulance')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_handovers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ambulance_handovers', to=settings.AUTH_USER_MODEL)),
                ('usage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='fleet.ambulanceusagerecord')),
            ],
        ),
    ]
