# Generated by Django 4.2.27 on 2026-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_ambulancehandoverchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='aa_zimbabwe_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='aa_zimbabwe_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='alarm_system_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='alarm_system_functional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='car_radio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='car_radio_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='floor_mats',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='floor_mats_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='hand_brake_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='hand_brake_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='lock_nuts_spanner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='lock_nuts_spanner_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='park_lights_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='park_lights_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='seat_belts_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='seat_belts_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='seat_covers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='seat_covers_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='spare_wheel_hatchet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='spare_wheel_hatchet_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='tool_box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='tool_box_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='vehicle_insurance_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='vehicle_insurance_disk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='vehicle_licence_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='vehicle_licence_disk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='view_mirrors_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='view_mirrors_functioning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='wheel_covers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='wheel_covers_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='wheel_spanner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ambulancehandoverchecklist',
            name='wheel_spanner_comments',
            field=models.TextField(blank=True),
        ),
    ]
