# Generated by Django 4.2.27 on 2026-02-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_ambulancehandoverchecklist_aa_zimbabwe_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverchecklist',
            name='checklist_type',
            field=models.CharField(choices=[('pickup', 'Pickup Inspection'), ('return', 'Return Inspection')], db_index=True, default='return', help_text='Whether this is a pickup or return checklist', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet.carrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='handoverchecklist',
            unique_together={('request', 'checklist_type')},
        ),
        migrations.AddIndex(
            model_name='handoverchecklist',
            index=models.Index(fields=['checklist_type', 'approval_status'], name='fleet_hando_checkli_273be0_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverchecklist',
            index=models.Index(fields=['request', 'checklist_type'], name='fleet_hando_request_78f959_idx'),
        ),
    ]
